public static class PhraseList
{
    public static string[] phrases =
    {
        "FUNemployment",
        "Has wires", "Has Red\nBackground", "Mostly black", "Has a\ncipher", "Flashes colors",
        "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages",
        "Skinny Wires", "Backgrounds", "The Digit", "Unfair Cipher", "Simon Speaks",
        "Complicated Wires", "Morsematics", "The Sphere", "Pigpen Cipher", "Simon Sings",
        "The Wire", "Faulty Backgrounds", "Labyrinth", "Playfair Cipher", "Flashing Lights",
        "Forget Enigma", "Forget Them All", "Periodic Table", "Vigenère Cipher", "Forget Me Not",
        "Perplexing Wires", "Simon's Stages", "Crystal Maze", "Morse Code", "The Sphere",
        "Wire Spaghetti", "Plumbing", "T-Words", "Maritime Flags", "Simon Stores",
        "Come again?",
        "Cardinals", "Flags", "Based on\nlength", "Feel this", "Listen up",
        "Semaphore", "Maritime", "Morse", "Braille", "Tap",
        "NESW", "French", "Pigpen", "Sphere", "..-.",
        "A compass", "Chess", "Lombax", "Plunger Button", "Dit dit dah dit",
        "North", "Don't click anything", "Pick this", "I don't want to", "2 1",
        "South", "USA", "Binary", "Tap code", "Lombax",
        "Weast", "Ternary", "Letters", "A Mistake", "Zoni",
        "Know Your Way", "The Necronomicon", "You're screwed", "Blind Alley", "Standard Galactic",
        "I don't\nunderstand",
        "A grid", "4 grids", "Letter\nPositioning", "WWII", "Shift by\na number",
        "Playfair", "Pigpen", "A1Z26", "Enigma", "Caesar",
        "Pigpen", "Playfair", "Binary", "Germany", "Augustus",
        "Coordinates", "Unfair", "Ternary", "Code Breaker", "Julius",
        "Tic-Tac-Toe", "Julius", "Caesar", "Caesar", "A1Z26",
        "Periodic Table of Elements", "Make it 3", "I before E, except after C", "You can't say that!", "Playfair",
        "404 Answer not found", "Bitmaps", "You will never win", "Playfair", "Ultimate",
        "ABDC", "Double-Oh", "Vigenere", "A1Z26", "Bamboozled Again",
        "Fade that",
        "Pull", "With a stick", "Hit me", "Even Minutes", "Cut them all",
        "Silly Slots", "Poker", "Blackjack", "Four-Card Monte", "Risky Wires",
        "A rope", "What?", "Bet", "Ice Cream", "Frisky Wires",
        "A Bop It", "A tree", "Stand", "I Scream", "It's okay",
        "The Switch", "Needy Crafting Table", "Poker", "Five-Card Monte", "Radical Wires",
        "Me up", "Mahjong", "Try Me", "Poker", "Radial Wires",
        "It out", "An effigy", "Barack Obama", "Hogwarts", "Tricky Wires",
        "Ed pork", "Zoo", "Jack Black", "Risky Wires", "Wires",
        "Unicode",
        "This Sucks", "<3", "You a letter", "4D", "Even Two's In",
        "Black Hole", "Tennis", "Simon Sends", "Hypercube", "Odd One Out",
        "A vacuum", "Golf", "Simon Speaks", "Ultracube", "Divide by 2",
        "You", "Basketball", "A letter", "The Cube", "Odd Two's Out",
        "A straw", "Bowling", "Simon Squeals", "The Sphere", "Even One Out",
        "Blackjack", "Soccer", "Simon Mails", "Lombax Cubes", "Odd One In",
        "A hole", "Hockey", "Simon Sings", "Rubik's Cube", "Even One In",
        "A whistle", "Football", "Simon Sucks", "Pattern Cube", "Odd Two's In",
        "Toilet Drain",
        "55555", "2006 was a\nrough year", "Crashed in 1929", "Based on\nStar Trek", "Welcome to\nGood Burger",
        "Quintuples", "Sonic the Hedgehog", "Stock Market", "Lightspeed", "Coffeebucks",
        "Quiplash", "Knuckles", "Me in Forza", "2001, A Space Odyssey", "Burger Alarm",
        "3125", "Sonic '06", "Pick me", "Star Wars", "Burglar Alarm",
        "Graffiti Numbers", "Mania", "Investors", "C", "Starbucks",
        "FIVE", "Forces", "Rock Market", "Falcon VI", "Pick the next answer",
        "Quadruplets", "Generations", "Cocked Musket", "Saturn V", "Wire Spaghetti",
        "Pentagonal", "Boom", "_______", "Apollo 11", "Retirement",
        "Think Time",
        "Flashes doubles\nand triples", "Solve for X", "Has Integrals", "Not Cruel", "Split up Darts",
        "Simon Stores", "Algebra", "Calculus", "Countdown", "X01",
        "Flashing Lights", "2", "Partial Derivatives", "Piano Keys", "puppy man made a mod",
        "Simon Stops", "X=Y", "Vectors", "Game of Life", "Splitting the Loot",
        "LED Math", "Calculus", "Prime Checker", "Purgatory", "X02",
        "Regular Crazy Talk", "Geometry", "No Comprende", "Mastermind", "X=1",
        "Crystal Maze", "Trigonometry", "Greek Calculator", "Ten Seconds", "X01 Power Armor",
        "Sphere", "Chronotrigger", "English Test", "Double-Oh", "Ex-Oh One",
        "Hmmmm",
        "A single line", "Colored Clues", "Contains Water", "Draws shapes", "Just two things",
        "The Witness", "Nonogram", "Battleship", "Shikaku", "Binary Puzzle",
        "Yarn", "Colo(u)r Talk", "A pool", "Nonogram", "Ternary Puzzle",
        "Victim", "Red", "The Sea", "Etch-a-Sketch", "Complimentary Puzzle",
        "A laser pointer", "Witness", "Destroyer", "Shuriken", "Ornery Puzzle",
        "The letter I", "Sudoku", "Ironclad", "Sudoku", "Octal Puzzle",
        "Ness's Wit", "1 3", "D4...hit", "Shish Kabob", "Scary Puzzle",
        "|", "Battleship", "Airplanes", "A pencil", "Contrary Puzzle",
        "You Lost",
        "Vanilla", "Work", "Not a Maze", "Logic", "Shaped",
        "<nothing>", "Factory", "Crystal", "Boolean", "Polyhedral",
        "Maze", "Industrial", "Diamond", "Arithme", "Polygon",
        "Labyrinth", "Revolutional", "Amethyst", "Super", "Pentagonal",
        "Network", "Scrambler", "Sapphire", "Al buttons", "Hexahedron",
        "Imbroglio", "USA", "Emerald", "Gates", "3D",
        "Hexa", "Module", "Topaz", "Venn Diagram", "Prismatoid",
        "3", "Mouse in the", "Lapis Lazuli", "Wires", "Icosahedron",
        "Pressed",
        "10", "1", "14", "5", "29",
        "Zoni", "Jack Attack", "Broken Buttons", "Double-Oh", "Pigpen Rotations",
        "Safety Square", "Memory", "Character Codes", "Tax Returns", "Modern Cipher",
        "Simon Stores", "Digital Root", "Colored Squares", "Morse Buttons", "Colorful Insanity",
        "LED Math", "Necronomicon", "Bartending", "Stack 'Em", "Simon's Simons",
        "The Code", "Witness", "The Moon", "Simon Scrambles", "Elder Futhark",
        "Mastermind", "Black Hole", "The Sun", "Colored Keys", "Shapes and Bombs",
        "Fast Math", "Number Pad", "Text Field", "Turtle Robot", "Cryptography",
        "C#",
        "Has Pins", "Fix errors", "Three Buttons", "Really Needy", "Hash It Out",
        "Microcontroller", "Scripting", "Web Design", "HTTP Response", "Turtle Robot",
        "Puzzle Box", "Script Wires", "CSS", "Ping", "Hash Browns",
        "A grenade", "A wrench", "HTML", "Pong", "#",
        "Sticky Notes", "A hammer", "Web Site", "HTML Response", "Pound Symbol",
        "A Bowling Alley", "!", "Scripting", "Coding Horribly", "Tic-Tac-Toe",
        "Ultracube", "#", "Web of Lies", "Microcontroller", "Tortoise Robot",
        "Hypercube", "Web Design", "Accept", "Refill That Beer!", "Tangrams",
        "See Sharp",
        "Feel it out", "Distances\nand gaps", "Simon ________", "Not broken", "Not cruel\nnor normal",
        "Rhythms", "Chord Qualities", "Sings", "Guitar Chords", "Festive Piano Keys",
        "Simon Sends", "Vectors", "Stores", "Simon Sounds", "Piano Keys",
        "Braille", "Coordinates", "Sends", "Double-Oh", "Guitar Chords",
        "Simon Sings", "Rhythms", "Spins", "Faulty Backgrounds", "Game of Life",
        "Listening", "Guitar Chords", "Stops", "Melody Sequencer", "Cursed Double-Oh",
        "Tap Code", "Piano Keys", "'s Stages", "A Mistake", "Cruel Piano Keys",
        "Coffeebucks", "Game of Life", "States", "Broken Guitar Chords", "Simon Says",
        "Identity Crisis",
        "Money", "In a Choir", "Yo No Comprende", "Like a record baby", "Morse Code",
        "Stores", "Sings", "Speaks", "Spins", "Sends",
        "Grocery Store", "Random", "¿Qué?", "Yeet", "Reverse Morse",
        "Cheap Checkout", "Piano is Better", "Spanish", "Jukebox", "Encrypted Morse",
        "Poker", "Sung", "Talks", "Sphere", "Morse-a-Maze",
        "Blackjack", "Sang", "Spoke", "Cube", "Morsematics",
        "Jewel Vault", "Shrieks", "SpeakingEvil", "Spinning Buttons", "Color Morse",
        "Splitting the Loot", "Screams", "Spank", "Bamboozled Again", "Samples",
        "Plug and Play",
        "Haduken", "Test Your Might", "Don't Drop It", "Fus Ro Dah", "GLORY",
        "Street Fighter", "Mortal Kombat", "Hot Potato", "Skyrim", "Passport Control",
        "Mortal Kombat", "Street Fighter", "Don't Tempt Me", "Unrelenting Force", "This Ain't a Game",
        "A Drunken Brawl", "Mega Man 2", "Rock Em Sock Em Robots", "Slow Time", "LEGOs",
        "A College Frat Party", "RPSLS", "Crackbox", "Ice Form", "Orientation Cube",
        "Mega Man 2", "Chess", "The Soap", "Dragonrend", "Word Search",
        "Some Anime or Somethin'", "The Gamepad", "X01", "Dismay", "Mystic Square",
        "Grown Men Punching Each Other", "Monsplode, Fight!", "Lucky Dice", "Disarm", "Chess"
    };
}