public static class PhraseList
{
    public static string[] phrases =
    {
        "FUNemployment",
        "Has wires", "Has Red\nBackground", "Mostly black", "Has a\ncipher", "Flashes colors", "Not me, but we", "ORDER (x3)", "Look Around",
        "Forget Them All", "Forget Me Not", "Souvenir", "Forget Enigma", "Simon's Stages", "Forget Us Not", "Organization", "Forget Perspective",
        "Skinny Wires", "Backgrounds", "The Digit", "Unfair Cipher", "Simon Speaks", "Communism", "Module Homewrk", "Perspective Pegs",
        "Complicated Wires", "Morsematics", "The Sphere", "Pigpen Cipher", "Simon Sings", "Not you, but I", "Burger Alarm", "Perspiration Pegs",
        "The Wire", "Faulty Backgrounds", "Labyrinth", "Playfair Cipher", "Flashing Lights", "Know Your Way", "Burglar Alarm", "Perspired Pegs",
        "Forget Enigma", "Forget Them All", "Periodic Table", "Vigenère Cipher", "Forget Me Not", "Forget Me Not", "Cooking", "Forget Perspiration",
        "Perplexing Wires", "Simon's Stages", "Crystal Maze", "Morse Code", "The Sphere", "Forget Enigma", "Organ Donor", "Rubik's Clock",
        "Wire Spaghetti", "Plumbing", "T-Words", "Maritime Flags", "Simon Stores", "Forget You", "Cookie Jar", "Rubik's Cube",
        "Come again?",
        "Cardinals", "Flags", "Based on\nlength", "Feel this", "Listen up", "You is 21", "Also a Cipher", "Speak with hands",
        "Semaphore", "Maritime", "Morse", "Braille", "Tap", "A1Z26", "Pigpen", "American Sign Language",
        "NESW", "French", "Pigpen", "Sphere", "..-.", "Barely Legal", "Playfair", "IS THAT A JOJO REFERENCE",
        "A compass", "Chess", "Lombax", "Plunger Button", "Dit dit dah dit", "Baba Is You", "Rail Fence", "RPSLS",
        "North", "Don't click anything", "Pick this", "I don't want to", "2 1", "I am not", "Caesar", "Claps",
        "South", "USA", "Binary", "Tap code", "Lombax", "Are, not is", "Number", "Snaps",
        "Weast", "Ternary", "Letters", "A Mistake", "Zoni", "Tap Code", "Digital", "ALS",
        "Know Your Way", "The Necronomicon", "You're screwed", "Blind Alley", "Standard Galactic", "Braille", "Vigenere", "American Signature Losers",
        "I don't\nunderstand",
        "A grid", "4 grids", "Letter\nPositioning", "WWII", "Shift by\na number", "On the right track", "Not a mountain", "Caesar's 13th",
        "Playfair", "Pigpen", "A1Z26", "Enigma", "Caesar", "Rail Fence", "Hill", "ROT13",
        "Pigpen", "Playfair", "Binary", "Germany", "Augustus", "Hill", "River", "Caesar",
        "Coordinates", "Unfair", "Ternary", "Code Breaker", "Julius", "Enigma", "Valley", "Unfair",
        "Tic-Tac-Toe", "Julius", "Caesar", "Caesar", "A1Z26", "Caesar", "Road", "Atbash",
        "Periodic Table of Elements", "Make it 3", "I before E, except after C", "You can't say that!", "Playfair", "ADFGVX", "Country", "Rail Fence",
        "404 Answer not found", "Bitmaps", "You will never win", "Playfair", "Ultimate", "Base 36", "Bump", "A1Z26",
        "ABDC", "Double-Oh", "Vigenere", "A1Z26", "Bamboozled Again", "Left", "Space", "Enigma",
        "Fade that",
        "Pull", "With a stick", "Hit me", "Even Minutes", "Cut them all", "Chinese Dictator", "Special Properties", "Roll five",
        "Silly Slots", "Poker", "Blackjack", "Four-Card Monte", "Risky Wires", "Point of Order", "Lucky Dice", "Yahtzee",
        "A rope", "What?", "Bet", "Ice Cream", "Frisky Wires", "Mao", "Yahtzee", "Nahtzee",
        "A Bop It", "A tree", "Stand", "I Scream", "It's okay", "Point of no return", "Point of Order", "Lucky Dice",
        "The Switch", "Needy Crafting Table", "Poker", "Five-Card Monte", "Radical Wires", "Blackjack", "Risky Wires", "Monopoly",
        "Me up", "Mahjong", "Try Me", "Poker", "Radial Wires", "Poker", "Poker", "Wire Placement",
        "It out", "An effigy", "Barack Obama", "Hogwarts", "Tricky Wires", "Mahjong", "Hogwarts", "Thing 1",
        "Ed pork", "Zoo", "Jack Black", "Risky Wires", "Wires", "Yahtzee", "Mahjong", "Thing 2",
        "Unicode",
        "This Sucks", "<3", "You a letter", "4D", "Even Two's In", "Wired Ring", "Memento Mori", "Professor Layton's Clue",
        "Black Hole", "Tennis", "Simon Sends", "Hypercube", "Odd One Out", "Follow The Leader", "Souvenir", "Pattern Cube",
        "A vacuum", "Golf", "Simon Speaks", "Ultracube", "Divide by 2", "Wire Placement", "Memory", "Who?",
        "You", "Basketball", "A letter", "The Cube", "Odd Two's Out", "Wires", "Horrible Memory", "Blue's Clue",
        "A straw", "Bowling", "Simon Squeals", "The Sphere", "Even One Out", "Black Hole", "Mad Memory", "The Cube",
        "Blackjack", "Soccer", "Simon Mails", "Lombax Cubes", "Odd One In", "The Wire", "Graphic Memory", "Orientation Cube",
        "A hole", "Hockey", "Simon Sings", "Rubik's Cube", "Even One In", "Wire Sequence", "Shape Memory", "Hypercube",
        "A whistle", "Football", "Simon Sucks", "Pattern Cube", "Odd Two's In", "Wire Spaghetti", "Forget Me Not", "Ultracube",
        "Toilet Drain",
        "55555", "2006 was a\nrough year", "Crashed in 1929", "Based on\nStar Trek", "Welcome to\nGood Burger", "bird", "A block", "Here comes\nthe clock...",
        "Quintuples", "Sonic the Hedgehog", "Stock Market", "Lightspeed", "Coffeebucks", "Swan", "The Cube", "Countdown",
        "Quiplash", "Knuckles", "Me in Forza", "2001, A Space Odyssey", "Burger Alarm", "Duck Duck Goose", "The Sphere", "Counting",
        "3125", "Sonic '06", "Pick me", "Star Wars", "Burglar Alarm", "Angry Birds", "The Troll", "The Clock",
        "Graffiti Numbers", "Mania", "Investors", "C", "Starbucks", "beard", "Algebra", "Rubik's Clock",
        "FIVE", "Forces", "Rock Market", "Falcon VI", "Pick the next answer", "burd", "Logic", "Timezone",
        "Quadruplets", "Generations", "Cocked Musket", "Saturn V", "Wire Spaghetti", "bird", "Cubic", "Timekeeper",
        "Pentagonal", "Boom", "_______", "Apollo 11", "Retirement", "berd", "Snooker", "Turn the Key",
        "Think Time",
        "Flashes doubles\nand triples", "Solve for X", "Has Integrals", "Not Cruel", "Split up Darts", "Fahrenheit 451", "2,3,5,7,11,13", "In your element",
        "Simon Stores", "Algebra", "Calculus", "Countdown", "X01", "Matchematics", "Prime Checker", "Periodic Table",
        "Flashing Lights", "2", "Partial Derivatives", "Piano Keys", "puppy man made a mod", "Countdown", "Square Checker", "Xenon",
        "Simon Stops", "X=Y", "Vectors", "Game of Life", "Splitting the Loot", "Morsematics", "Connection Check", "Neon",
        "LED Math", "Calculus", "Prime Checker", "Purgatory", "X02", "SUPER HOT", "Radiator", "Rubidium",
        "Regular Crazy Talk", "Geometry", "No Comprende", "Mastermind", "X=1", "Manometers", "Number", "Sodium",
        "Crystal Maze", "Trigonometry", "Greek Calculator", "Ten Seconds", "X01 Power Armor", "Number Cipher", "Cruel Purgatory", "Bismuth",
        "Sphere", "Chronotrigger", "English Test", "Double-Oh", "Ex-Oh One", "Black Hole", "Color Morse", "Potassium",
        "Hmmmm",
        "A single line", "Colored Clues", "Contains Water", "Draws shapes", "Just two things", "6 colors", "A Bug's Life", "Ancient Chinese Puzzle",
        "The Witness", "Nonogram", "Battleship", "Shikaku", "Binary Puzzle", "Rubik's Cube", "Langton's Ant", "Tangram",
        "Yarn", "Colo(u)r Talk", "A pool", "Nonogram", "Ternary Puzzle", "Rubik's Clock", "Pant", "Nonogram",
        "Victim", "Red", "The Sea", "Etch-a-Sketch", "Complimentary Puzzle", "Pattern Cube", "Liechtenstein", "Binary",
        "A laser pointer", "Witness", "Destroyer", "Shuriken", "Ornery Puzzle", "Cube", "Hexamaze", "Shikaku",
        "The letter I", "Sudoku", "Ironclad", "Sudoku", "Octal Puzzle", "Sphere", "Matrix", "Sudoku",
        "Ness's Wit", "1 3", "D4...hit", "Shish Kabob", "Scary Puzzle", "Rubik's Sphere", "Hornet's Nest", "Battleship",
        "|", "Battleship", "Airplanes", "A pencil", "Contrary Puzzle", "Press F", "The Giant's Drink", "Witness",
        "You Lost",
        "Vanilla", "Work", "Not a Maze", "Logic", "Shaped", "Greek for 6", "Like Tunnels", "Not Deaf",
        "<nothing>", "Factory", "Crystal", "Boolean", "Polyhedral", "Hexa", "3D", "Blind",
        "Maze", "Industrial", "Diamond", "Arithme", "Polygon", "6", "The Sewer", "Dead",
        "Labyrinth", "Revolutional", "Amethyst", "Super", "Pentagonal", "Hexagonal", "The City", "Mute",
        "Network", "Scrambler", "Sapphire", "Al buttons", "Hexahedron", "Honey Comb", "A hole", "Dumb",
        "Imbroglio", "USA", "Emerald", "Gates", "3D", "Hexabutton", "Necronomicon", "Alley",
        "Hexa", "Module", "Topaz", "Venn Diagram", "Prismatoid", "Icosahedron", "A pool", "Deaf",
        "3", "Mouse in the", "Lapis Lazuli", "Wires", "Icosahedron", "VI", "Plumbing", "Maze",
        "Pressed",
        "10", "1", "14", "5", "29", "3-7", "118", "0",
        "Zoni", "Jack Attack", "Broken Buttons", "Double-Oh", "Pigpen Rotations", "Polyhedral Maze", "Periodic Table", "Boolean Wires",
        "Safety Square", "Memory", "Character Codes", "Tax Returns", "Modern Cipher", "Double-Oh", "Forget Enigma", "Snap!",
        "Simon Stores", "Digital Root", "Colored Squares", "Morse Buttons", "Colorful Insanity", "Safety Square", "Qwirkle", "Lombax Cubes",
        "LED Math", "Necronomicon", "Bartending", "Stack 'Em", "Simon's Simons", "Insanagrams", "Colour Code", "Forget This",
        "The Code", "Witness", "The Moon", "Simon Scrambles", "Elder Futhark", "Treasure Hunt", "Hidden Colors", "Micro-Modules",
        "Mastermind", "Black Hole", "The Sun", "Colored Keys", "Shapes and Bombs", "Book of Mario", "Pigpen Rotations", "Genetic Sequence",
        "Fast Math", "Number Pad", "Text Field", "Turtle Robot", "Cryptography", "Antichamber", "Modern Cipher", "Factory Maze",
        "C#",
        "Has Pins", "Fix errors", "Three Buttons", "Really Needy", "Hash It Out", "It grows", "404", "Not Nand Nor",
        "Microcontroller", "Scripting", "Web Design", "HTTP Response", "Turtle Robot", "Binary Tree", "Error Codes", "Logic Gates",
        "Puzzle Box", "Script Wires", "CSS", "Ping", "Hash Browns", "Creation", "Answer not found", "Boolean Venn Diagram",
        "A grenade", "A wrench", "HTML", "Pong", "#", "Ice Cream", "Base 5", "Arithmelogic",
        "Sticky Notes", "A hammer", "Web Site", "HTML Response", "Pound Symbol", "A child", "101x4", "Superlogic",
        "A Bowling Alley", "!", "Scripting", "Coding Horribly", "Tic-Tac-Toe", "A plant", "An error", "Logic",
        "Ultracube", "#", "Web of Lies", "Microcontroller", "Tortoise Robot", "The debt of college students", "Error efficiency", "Logical Buttons",
        "Hypercube", "Web Design", "Accept", "Refill That Beer!", "Tangrams", "The number of Simons", "Error", "Boolean Maze",
        "See Sharp",
        "Feel it out", "Distances\nand gaps", "Simon ________", "Not broken", "Not cruel\nnor normal", "Listen Up", "Swap Around", "Hardware Store",
        "Rhythms", "Chord Qualities", "Sings", "Guitar Chords", "Festive Piano Keys", "Harmony Sequence", "Melody Sequencer", "Weird Al Yankovic",
        "Simon Sends", "Vectors", "Stores", "Simon Sounds", "Piano Keys", "Chord Qualities", "Piano Keys", "Weird Al",
        "Braille", "Coordinates", "Sends", "Double-Oh", "Guitar Chords", "Simon Sends", "Guitar Chords", "Spinning Buttons",
        "Simon Sings", "Rhythms", "Spins", "Faulty Backgrounds", "Game of Life", "Simon Sings", "Game of Life", "The Screw",
        "Listening", "Guitar Chords", "Stops", "Melody Sequencer", "Cursed Double-Oh", "Melody Sequencer", "Harmony Sequencer", "Wires",
        "Tap Code", "Piano Keys", "s Stages", "A Mistake", "Cruel Piano Keys", "Jukebox", "Festive Piano Keys", "A Mistake",
        "Coffeebucks", "Game of Life", "States", "Broken Guitar Chords", "Simon Says", "Piano Keys", "Matchematics", "Stack 'Em",
        "Identity Crisis",
        "Money", "In a Choir", "Yo No Comprende", "Like a record baby", "Morse Code", "Your eggs", "Like a sign", "Synonym for Noises",
        "Stores", "Sings", "Speaks", "Spins", "Sends", "Scambles", "Stops", "Sounds",
        "Grocery Store", "Random", "¿Qué?", "Yeet", "Reverse Morse", "Sucks", "Spin", "Screams",
        "Cheap Checkout", "Piano is Better", "Spanish", "Jukebox", "Encrypted Morse", "Screwed", "Star", "Sings",
        "Poker", "Sung", "Talks", "Sphere", "Morse-a-Maze", "Cooks", "Spins", "Stores",
        "Blackjack", "Sang", "Spoke", "Cube", "Morsematics", "Cracks", "Stores", "Hubbub",
        "Jewel Vault", "Shrieks", "SpeakingEvil", "Spinning Buttons", "Color Morse", "Creams", "Red", "Pancreatic Pain",
        "Splitting the Loot", "Screams", "Spank", "Bamboozled Again", "Samples", "Smacks", "Octagonal", "Superman",
        "Plug and Play",
        "Haduken", "Test Your Might", "Don't Drop It", "Fus Ro Dah", "GLORY", "Build em", "Made of Paper", "Knight to I quit",
        "Street Fighter", "Mortal Kombat", "Hot Potato", "Skyrim", "Passport Control", "Legos", "Book of Mario Thousands of Doors", "Chess",
        "Mortal Kombat", "Street Fighter", "Don't Tempt Me", "Unrelenting Force", "This Ain't a Game", "Stack 'Em", "RPSLS", "Knight",
        "A Drunken Brawl", "Mega Man 2", "Rock Em Sock Em Robots", "Slow Time", "LEGOs", "Duplo Blocks", "Nonogram", "Queen",
        "A College Frat Party", "RPSLS", "Crackbox", "Ice Form", "Orientation Cube", "Block Stacks", "A boat", "King",
        "Mega Man 2", "Chess", "The Soap", "Dragonrend", "Word Search", "Simon Says", "Mod Homework", "Bishop",
        "Some Anime or Somethin'", "The Gamepad", "X01", "Dismay", "Mystic Square", "Monsplode etc", "Organization", "Rook",
        "Grown Men Punching Each Other", "Monsplode, Fight!", "Lucky Dice", "Disarm", "Chess", "Chess", "The previousanswer was correct", "Pawn",
        "Electric Boogaloo",
        "x^2", "Dot Dah Dit Dash", "Rectangular Bars", "Simon's Whole\nFamily", "Rotations", "Remember\nthe Clue", "Pointy Colors", "Mental",
        "Colored Squares", "Morsematics", "Ordered Keys", "Simon States", "Caesar Cycle", "Forget Me Not", "Red Arrows", "Crazy Talk",
        "Decolored Squares", "Morse Code", "Unordered Keys", "Simon Screams", "Affine Cycle", "Forget Everything", "Yellow arrows", "Who's On First",
        "Varicolored Squares", "Color Morse", "Reordered Keys", "Simon Says", "Symbol Cycle", "Forget This", "Blue Arrows", "Regular Crazy Talk",
        "Divided Squares", "Morse-A-Maze", "Misordered Keys", "Simon Sounds", "Pigpen Cycle", "Forget Them All", "Orange Arrows", "Krazy Talk",
        "Mystic Square", "Morse War", "Bordered Keys", "Simon Seduces", "Playfair Cycle", "Forget Enigma", "Purple Arrows", "Insane Talk",
        "Square Button", "Reverse Morse", "Recorded Keys", "Simon's Stages", "Jumble Cycle", "Forget Us Not", "Double Arrows", "Colo(u)r Talk",
        "Uncolored Squares", "Encrypted Morse", "Turn the Key", "United States", "Cryptic Cycle", "Memory", "Annoying Arrows", "Third Base",
        "Masquerade",
        "Where you eat", "Where you cook", "Where you work", "Where you relax", "Snooker", "Like a Greenhouse", "Panic! at the Disco", "Connects Room",
        "Dining Room", "Kitchen", "Study", "Lounge", "Billiard Room", "Conservatory", "Ballroom", "Hall",
        "Kitchen", "McDonald", "Office", "Bed", "Pool room", "Violet you glad", "Danceroom", "Floorplan",
        "Bedroom", "Dining Room", "School", "This is Incorrect...", "Pool", "Blue you glad", "Disco", "Door",
        "Patio", "Patio", "Work", "Lunge", "Bedroom", "Green you glad", "Disco Ball", "Window",
        "Hall", "Backyard", "Home", "Home", "I hardly know 'er", "Yellow you glad", "Nirvana", "Hallway",
        "Conservatory", "Oven", "Kitchen", "Ballroom", "Royal_Flu$h", "Orange you glad", "Weird Al Yankovic", "In the Hall of the Mountain King",
        "McDonalds", "Microwave", "Story", "Hall", "Remember Souvenir", "Red you glad", "High Hopes", "Conveyor Belt",
        "Forget Me Not",
        "Math and Logic", "Circle of Life", "Not Fair!", "Luna", "Satanic Ritual", "America", "Initial Name\nof Simon Sends", "NaCl",
        "Arithmelogic", "Big Circle", "Unfair Cipher", "The Moon", "Necronomicon", "USA Maze", "Color Morse", "Neutralization",
        "Logic", "Lion's Share", "Playfair Cipher", "The Sun", "Library", "Factory Maze", "Simon Stores", "Periodic Table",
        "Fast Math", "The Sphere", "Playfair Cycle", "Black Hole", "Hell", "United States Maze", "Simon's Stanky Leg", "Neuterization",
        "Unfair Cipher", "Poetry", "The Cube", "Planets", "Book of Belial", "USD Maze", "Simon Stages", "Nepotism",
        "Skewed Slots", "The Clock", "Simon Stores", "The Eclipse", "Book of Revelations", "Red, White and Blue", "Simon Steps", "Nihonium",
        "Silly Slots", "Rubik's Clock", "Sphere", "Jack Attack", "Book Worm", "Flags", "Simon Stops", "Nut Busters 2: Electric Boogaloo",
        "Snooker", "Simon Spins", "Unfair Cycle", "Midnight", "Necronomomom", "Spell ICUP and this bomb will solve", "Simon Sucks", "Press This",
        "Potassium",
        "Colorful\nMadness Talk", "A Dandy Lion", "Remember\nthe Clue...", "100 cents\nin a dollar", "They've got\nAllen Wrenches", "REDDITOR", "Turn the Key", "Game of The Year",
        "Colo(u)r Talk", "Flower Patch", "Jack Attack", "Common Sense", "Weird Al Yankovic", "Bone Apple Tea", "Timing is Everything", "Garfield Kart",
        "Red Arrows", "Daphidil", "Souvenir", "USD", "Jukebox", "Go Commit Die", "Turn the Keys", "Skyrim",
        "Green Arrows", "How do I spell daphedil?", "Forget Me Not", "Common Scent", "Festive Jukebox", "Mildly Vandalised", "burh", "Sonic the Hedgehog",
        "Crazy Talk", "Daphy Duck", "Forget Them All", "Transaction", "Toilet Seats, Electric Heaters", "I am 14 and this is Deep", "Timing in Nothing", "Sonic and Knuckles",
        "Color Talk", "Daphodil", "Forget Enigma", "Baconian Cipher", "Trash Compactors", "Dad Jokes", "Tmng s vrthing", "Poetry",
        "Colour Talk", "Dfdl", "FORGET JACK", "But I'm British/Australian", "Juice Extractors", "Shower Thoughts", "fghadfjsadfadf", "Antichamber",
        "Yellow Arrows", "D", "Forget Perspective", "Make it fiddy", "Shower Rods and Parking Meters", "Rare Insults", "Burge Khalifa", "Pong",
        "It's Too\nDangerous\nto Go Alone",
        "Four in Two", "Alcohol", "Shape Shift\nis Flat ____", "You'll\nFloat Too...", "Same as\nlooking at Log", "Aerodynamic", "IKEA", "_____ Cycle",
        "Battery", "Potion", "Ticket", "Balloon", "Cheat Code", "Feather", "Lamp", "Symbol",
        "Lit Bob", "Beer", "Round", "In 1972, a crack clown unit was sent to prison by a circus court for a crime", "EFM CENTURION TIME", "Air Traffic Controller", "qSwedishMaze", "Garfield Kart",
        "Parallel", "Whiskey", "Point", "God", "Logistics Analyzer", "Jet Engine", "IKEA", "Garfield Kart.",
        "Serial", "Bartending", "Flat", "I went to Taco Bell and tried to spend a $2 bill, and the cashier had no idea what it was and called the cops.", "Cheat Mode", "A cannonball", "Moonstone", "Garfield Kart...",
        "PS/2", "Vodka", "Spherical", "Snake... why are we still here? Just to suffer? Every night, I can feel my leg and my arm... even my fingers... the body I've lost... the comrades I've lost... won't stop hurting.", "Logfile Analyzer", "A Small Child", "Masyu", "Garfield Kart!",
        "RJ-45", "Wine", "Triangle", "You are not a prick you are the entire cactus.", "I can't think of anymore wrong answers", "Fruits", "Burh", "Garfield Kart?",
        "On one Plate", "21st Amendment", "Polar Express", "You are not a clown you are the entire circus.", "up up down down left right left right B A start", "A Grenade", "Witness", "GARFIELD KART",
        "Do as I say,\nand you'll make\nit through...",
        "Pick The\nFirst Option", "Pick Nothing", "Pick Me Up", "Pick Whatever\nYou Want", "Pick The\nSecond Option", "Pick Multiplication\nSymbol", "Pick This", "Pick Pick This",
        "The First Option", "Nothing", "Me Up", "Whatever You Want", "The Second Option", "Multiplication Symbol", "This", "Pick This",
        "First Option", "__________", "Me Not", "Freedom is Great", "The First Option", ".", "That", "Pick That",
        "You missed it", "<_________>", "Me Now", "Garfield Kart", "The Third Option", "X", "Those", "Pick Those",
        "The Second Option", "Blank", "Alcohol", "Macdondalds", "Second Option", "x", "These", "Pick These",
        "Pick This", "(Nothing)", "I'd rather not...", "I be straight boo walking", "The Fourth Option", "Times", "Thesis", "Pick Thesis",
        "Pick the Next Option", ".", "Pick This", "I will LeBron James Dunk on You", "The Fifth Option", "Multiplied", "Thisis", "Pick Thoses",
        "Pick the Last Option", "", "Pick Nothing", "Skip This Section", "The Sixth Option", "*", "Parenthesis", "This",
        "Hellraiser",
        "Calculators at\nthe ready...", "Every 10 seconds,\na button must\nbe pushed", "Julius Spins\nYou Right Round", "A 4x4 of Pain", "3 stages", "00", "Scrooge", "After Penultimate",
        "Simon Stores", "The Very Annoying Button", "Caesar Cycle", "Bamboozling Button Grid", "Ordered Keys", "Double Arrows", "Cryptic Cycle", "Ultimate Cycle",
        "Fast Math", "Swan", "Affine Cycle", "Bamboozled Again", "Unordered Keys", "Double Oh", "Cryptography", "Cryptic Cycle",
        "Emoji Math", "Double Arrows", "Hill Cycle", "Bamboozling Button", "Reordered Keys", "Cursed Double Oh", "Cryptogram", "Hill Cycle",
        "Fizzbuzz", "The Very Antagonizing Button", "Pigpen Cycle", "BAMG", "Misordered Keys", "Double-Oh", "LED Encryption", "Caesar Cycle",
        "Encrypted Equations", "Swan 2: Elected Boog", "Playfair Cycle", "BAMA", "Bordered Keys", "Cursed Double-Oh", "Encrypted Morse", "Affine Cycle",
        "Accumulation", "Purple", "Jumble Cycle", "BAMB", "Disordered Keys", "Red Arrows", "Cryptic Password", "Pigpen Cycle",
        "Simon's Star", "TVAB", "Ultimate Cycle", "Bamboolean Venn Diagram", "Tallordered Keys", "Black Arrows", "Encrypted Indicators", "Playfair Cycle",
        "I choose you",
        "Crashes Zen Mode", "Percy Can't\nHandle Sillyness", "First in\nX's and O's", "A mystery...", "FRQ and FRK", "Door to Hell", "Here comes\nthe clock...", "Duracells and\nEnergizers",
        "Boom", "Splash", "Tic", "Defuse", "Freak Out", "Dark Portal", "Countdown", "Battery Power",
        "Boo", "Puppy", "Tac", "Diffuse", "Frisky", "Doom", "Finale", "Last Word",
        "Doom", "Magikarp", "Toe", "Void", "Void", "Shrink", "Boom", "Hardware Store",
        "Yabba Dabba Doom!", "Shock", "Bug Spray", "Battery Power", "Sidestep", "Last Word", "Bug Spray", "Weird Al Yankovic",
        "Finale", "Shrink", "Tick", "Freak Out", "Finale", "Boom", "Sidestep", "Hollow Gaze",
        "Fiery Soul", "Defuse", "X", "Dark Portal", "Shock", "Glyph", "Candle", "Torchlight",
        "Glyph", "Void", "O", "Tic", "Boom", "Appearify", "Cave In", "Splash",
        "Road Rage",
        "Hispanic Hulk Man", "Masked Muscle", "Unknown Origins", "Female", "Russian", "Has An Eyepatch", "Marked all over", "Blonde",
        "Blanka", "Vega", "M. Bison", "Chun Li", "Zangief", "Sagat", "Dhalsim", "Ken",
        "Hulk", "Punch Out!!", "Joker", "Sonya Blade", "Putin", "Solid Snake", "Great Tiger", "Blanka",
        "Beanstalk", "Jason", "Godot", "D'Vorah", "Lenin", "Elon Musk", "Anyone in Hellraiser", "Zangief",
        "Hulk, but from Spain", "Michael Myers", "Superman", "Cassie Cage", "Soda Popinski", "That dude from Avengers", "Pac Man", "Fred",
        "Hulk, but from Brazil", "Boba Fett", "Goofy", "Jade", "Zodiac", "Captain Haddock", "A whiteboard", "Mercy",
        "Blanco", "Batman", "Shaggy", "Kitana", "No Russian", "Blackbeard", "A chalkboard", "Johnny Bravo",
        "Blananas2", "Jared Leto Joker", "Garfield", "Mileena", "Revolver Ocelot", "A half blind man", "A blackboard", "Chad",
        "This is incorrect...",
        "You", "Dispenses Water", "Should Play Music", "Two Submits", "Should add up\nall digits", "Should be\nyour computer screen\nwith nothing open", "Should Know\nYour Way", "Almost Senile",
        "A Mistake", "Faulty Sink", "Broken Guitar Chords", "Broken Buttons", "Faulty Digital Root", "Faulty Backgrounds", "Faulty RGB Maze", "Old Fogey",
        "Wonderful", "Sink", "Guitar Chords", "CONFIRM", "Digital Root", "Backgrounds", "Know Your Way", "You",
        "Glamourous", "Hose", "Piano Keys", "Boot Too Big", "Cruel Digital Root", "Pong", "RGB Maze", "Double-Oh",
        "Cheerful", "IKEA", "Festive Piano Keys", "Cruel Digital Root", "Countdown", "Black", "Mazes", "Cursed Double-Oh",
        "Good at the game", "Plumbing", "Cruel Piano Keys", "Digital Root", "Cruel Countdown", "Quiz Buzz", "Factory Maze", "Morse Code",
        "Serious", "Battleship", "Melody Sequencer", "Antichamber", "Simon Stores", "A bomb walks into a bar...", "Labyrinth", "Semaphore",
        "Funny", "Treasure Hunt", "Harmony Sequence", "Toon Enough", "A calculator", "Binary", "Party Time", "Old Funky",
        "Mystical",
        "Lit BOB\n4 in 2", "6 in 3\nLit BOB", "Lit BOB\n4 in 3", "Defuse", "All the same", "Jack Attack", "Only Lit BOB\n& 2 Batteries", "The date is\nApril, 9th",
        "Laundry", "Game of Life Cruel", "Morse-A-Maze", "Monsplode, Fight!", "Yahtzee", "This", "Unfair Cipher", "Double Expert",
        "Game of Life Simple", "Game of Life Simple", "Laundry", "Monsplode Trading Cards", "Lucky Dice", "Not this", "Game of Life Cruel", "Double-Oh",
        "Game of Life Cruel", "Game of Life", "Bamboozled Again", "Who's that Monsplode", "Forget Us Not", "Not this", "Laundry", "Follow the Leader",
        "Morse-A-Maze", "Laundry", "Jack Attack", "Now", "A Mistake", "Not this", "Morse-A-Maze", "Cooking",
        "Unfair Cipher", "Morse-A-Maze", "Bomb Diffusal", "Answer!", "Simon Stores", "Not this", "Jack Attack", "Hyperlink",
        "Double Expert", "Bob Barks", "Seven Deadly Sins", "Confirm!", "DetoNATO", "Not this", "English Test", "Lion's Share",
        "Garfield Kart", "Kudosudoku", "The Matrix", "Pick this", "Krazy Talk", "Not this", "Nut-o-Matic", "The Sphere",
        "Echolocation", "The Hyperlink", "Bob Barks", "UltraStores", "PogChamp", "Not this", "Who's BOB again?", "Square Button"
    };
}
